vich_uploader:
    db_driver: orm

    mappings:
        protocolFile:
            uri_prefix: '%app.path.protocols%'
            upload_destination: '%kernel.project_dir%/public%app.path.protocols%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        test_image:
            uri_prefix: '%app.path.protocols%'
            upload_destination: '%kernel.project_dir%/public%app.path.protocols%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

