vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    mappings:
        protocol_file:
            uri_prefix: '%app.path.protocols%'
            upload_destination: '%kernel.project_dir%/public%app.path.protocols%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        test_image:
            uri_prefix: '%app.path.protocols%'
            upload_destination: '%kernel.project_dir%/public%app.path.protocols%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

