<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'SYMFONY_DOTENV_PATH' => './.env',
  'APP_SECRET' => 'dad7f95aa6c8ab593ed9176336272efd',
  'APP_CSP_ENABLED' => 'off',
  'MAILER_DSN' => 'null://null',
  'DATABASE_URL' => 'sqlite:///%kernel.project_dir%/var/data.db',
);
