insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (1, 1, 'TR', 1);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (2, 1, 'TE', 1);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (3, 2, 'PitchFactor', 1);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (4, 2, 'QualityRefMAs', 1);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (5, 2, 'RefKV', 1);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (6, 2, 'Voltage', 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (7, 2, 'CustomMAs', 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (8, 2, 'CustomMAsA', 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (9, 2, 'CustomMAsB', 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (10, 2, 'CarekV', 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (11, 2, 'OptimizeSliderPosition', 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (12, 2, 'Care', 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (13, 2, 'CareDoseType', 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (14, 2, 'CTDIw', 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (15, 2, 'DLP', 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (16, 2, 'FastAdjustLimitScanTime', 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (17, 2, 'FastAdjustLimitMaxMAs', 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (18, 2, 'DoseNotificationValueCTDIvol', 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (19, 2, 'oseNotificationValueDLP', 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (20, 2, 'RotTime', 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (21, 2, 'ScanTime', 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (22, 2, 'Delay', 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (23, 2, 'Feed', 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (24, 2, 'SliceEffective', 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (25, 2, 'Acq.', 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected) values (26, 2, 'ReconSliceEffective', 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected, parameter_default) values (27, 2, 'ReconIncrR', 0, 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected, parameter_default) values (28, 2, 'NoOfImages', 0, 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected, parameter_default) values (29, 2, 'Kernel', 1, 1);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected, parameter_default) values (30, 2, 'Window', 1, 1);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected, parameter_default) values (31, 2, 'ApiId', 0, 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected, parameter_default) values (32, 2, 'Comment1', 0, 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected, parameter_default) values (33, 2, 'Comment2', 0, 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected, parameter_default) values (34, 2, 'Transfer1', 0, 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected, parameter_default) values (35, 2, 'Transfer2', 0, 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected, parameter_default) values (36, 2, 'Transfer3', 0, 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected, parameter_default) values (37, 2, 'SyngoViaTaskflow', 0, 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected, parameter_default) values (38, 2, 'SyngoViaProcessingID', 0, 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected, parameter_default) values (39, 2, 'ScanStart', 0, 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected, parameter_default) values (40, 2, 'ScanEnd', 0, 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected, parameter_default) values (41, 2, 'Pulsing', 0, 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected, parameter_default) values (42, 2, 'PulsingStart', 0, 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected, parameter_default) values (43, 2, 'PulsingEnd', 0, 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected, parameter_default) values (44, 2, 'BestPhase', 0, 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected, parameter_default) values (45, 2, 'PhaseStart', 0, 0);
insert into main.parameter (parameter_id, geraet_id, parameter_name, parameter_selected, parameter_default) values (46, 2, 'Multiphase', 0, 0);
